name: edge2

on:
  push:
    branches: [ "main" ]
    paths:
      - edge2/**
  pull_request:
    branches: [ "main" ]
    paths:
      - edge2/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: ./edge2/build.sh 
