name: main

on:
  push:
    branches: [ "main" ]
    paths:
      - edge2/**
  pull_request:
    branches: [ "main" ]
    paths:
      - edge2/**

jobs:

  edge2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: ./edge2/build.sh 

  ci-pipeline:
    runs-on: ubuntu-latest
    needs: edge2
    steps:
      - name: Final
        run: echo "Finished!"
