name: main

on:
  push:
    branches: [ "main" ]
    paths:
      - edge1/**
  pull_request:
    branches: [ "main" ]
    paths:
      - edge1/**

jobs:

  edge1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: ./edge1/build.sh 

  ci-pipeline:
    runs-on: ubuntu-latest
    needs: edge1
    steps:
      - name: Final
        run: echo "Finished!"
